MAKEFILE_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
CURRENT_DIR := $(notdir $(patsubst %/,%,$(dir $(MAKEFILE_PATH))))
SRC_FOLDER= $(dir $(MAKEFILE_PATH))src/
INCLUDE_FOLDER= $(dir $(MAKEFILE_PATH))include/
LIB_FOLDER= $(dir $(MAKEFILE_PATH))lib/
BIN_FOLDER= $(dir $(MAKEFILE_PATH))bin/
MKDIR_P = mkdir -p

CC=g++
CFLAGS=-c -Wall -I$(INCLUDE_FOLDER) -std=c++11
.SUFFIXES: .cxx .cpp
LDFLAGS=-lpthread -ltins -lpcap -L$(LIB_FOLDER)

SOURCES=$(SRC_FOLDER)main.cxx $(SRC_FOLDER)HerbivoreUtils.cxx $(SRC_FOLDER)HerbParser.cxx  $(SRC_FOLDER)HerbSniffer.cxx
OBJECTS=$(SOURCES:.cxx=.o)
EXECUTABLE=$(BIN_FOLDER)herb_commands

all:  $(BIN_FOLDER) $(SOURCES) $(EXECUTABLE) $(SRC_FOLDER)Herbivore_wrap.cxx


$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

$(SRC_FOLDER)Herbivore_wrap.cxx:$(SRC_FOLDER)Herbivore.i
	swig -c++ -javascript -node -DV8_VERSION=0x050071 $(SRC_FOLDER)Herbivore.i

.cxx.o:
	$(CC) $(CFLAGS) $< -o $@

$(BIN_FOLDER):
	$(MKDIR_P) $(BIN_FOLDER)

clean:
	rm $(EXECUTABLE) $(OBJECTS)
	rm $(SRC_FOLDER)Herbivore_wrap.cxx