CC=g++
CFLAGS=-c -Wall -Iinclude/ -std=c++11
.SUFFIXES: .cxx .cpp
LDFLAGS=-lpthread -ltins -lpcap -Llib/
SOURCES=src/main.cxx src/HerbivoreUtils.cxx src/HerbParser.cxx  src/HerbSniffer.cxx
OBJECTS=$(SOURCES:.cxx=.o)
EXECUTABLE=bin/herb_commands

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cxx.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm $(EXECUTABLE) $(OBJECTS)